version: "3.8"

volumes:
  prometheus:
  grafana:

services:

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      [
        '--log.level=debug',
        '--config.file=/etc/prometheus/prometheus.yml',
        '--enable-feature=remote-write-receiver',
        '--query.lookback-delta=30s'
      ]

  # for testing purposes only, disable in production
  log-generator:
    image: mingrammer/flog
    command:
      - --loop
      - --format=json
      - --number=10 # number of log lines to generate per second
      - --delay=100ms # delay between log lines
      - --output=/var/log/generated-logs.txt
      - --overwrite
      - --type=log
    volumes:
      - ./logs/:/var/log/

  loki:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/loki-read.yaml:/etc/loki/loki-read.yaml
      - ./config/loki-write.yaml:/etc/loki/loki-write.yaml
      - ./config/loki-backend.yaml:/etc/loki/loki-backend.yaml
      - ./loki:/tmp/loki/
    ports:
      - "8080:8080"