apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://loki:8080
    version: 1

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 1