global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
      - names:
          - prometheus
        type: A
        port: 9090

  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - loki
        type: A
        port: 8080
